# -*- coding: utf-8 -*-
"""Writes the drill lessons that fill in whatever syllables the hand-written
ones miss.

The graded lessons in drills/lessons.txt are prose and only reach the
syllables prose happens to use -- about 59% of single-character usage. The
rest has to come from somewhere, so this picks real two-character words out
of the dictionary by greedy set cover: at each step, the word that covers
the most still-uncovered syllables wins, breaking ties by how common the
word is.

Deliberately stops at a usage threshold rather than at every syllable in the
dictionary: the tail is ㄋㄩㄝ and ㄌㄩㄢ, which nobody types (2026-08-09).

    python scripts/make-filler-lessons.py --data out/data.txt \
        --covered out/drill-syllables.txt --out drills/filler.txt
"""

import argparse
import collections
import io
import math
import os

TONE_MARKS = ("ˊ", "ˇ", "ˋ", "˙")

# Below this score a dictionary entry is a word the learner will never meet;
# drilling it would teach the keys with an unreadable example.
MIN_WORD_SCORE = -8.0
# Fraction of single-character usage the drills should be able to type.
USAGE_TARGET = 0.99

WORDS_PER_SENTENCE = 5
SENTENCES_PER_LESSON = 7


def bare(reading):
    for mark in TONE_MARKS:
        if reading.endswith(mark):
            return reading[: -len(mark)]
    return reading


def code_points(text):
    return list(text)


def load(path):
    """Returns (syllable mass, two-character word list)."""
    mass = collections.Counter()
    # value -> list of (reading, score); a word with several readings is
    # skipped, so the generator's own pick can never disagree with ours.
    by_value = collections.defaultdict(list)
    with io.open(path, encoding="utf-8") as handle:
        for line in handle:
            if not line.strip() or line.startswith("#"):
                continue
            fields = line.split()
            if len(fields) < 3 or "_" in fields[0]:
                continue
            reading, value = fields[0], fields[1]
            try:
                score = float(fields[2])
            except ValueError:
                continue
            syllables = reading.split("-")
            if len(code_points(value)) != len(syllables):
                continue
            if len(syllables) == 1:
                mass[bare(reading)] += math.exp(score)
            by_value[value].append((reading, score))

    words = []
    for value, readings in by_value.items():
        if len(value) != 2 or len(readings) != 1:
            continue
        reading, score = readings[0]
        if score < MIN_WORD_SCORE:
            continue
        words.append((value, reading.split("-"), score))
    return mass, words


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", default="out/data.txt")
    parser.add_argument("--covered", default="out/drill-syllables.txt")
    parser.add_argument("--out", default="drills/filler.txt")
    args = parser.parse_args()

    mass, words = load(args.data)

    covered = set()
    if os.path.exists(args.covered):
        with io.open(args.covered, encoding="utf-8") as handle:
            covered = {line.strip() for line in handle if line.strip()}

    # The syllables worth drilling: the common end of the distribution.
    total = sum(mass.values())
    running = 0.0
    wanted = set()
    for syllable, weight in mass.most_common():
        wanted.add(syllable)
        running += weight
        if running / total >= USAGE_TARGET:
            break
    todo = wanted - covered

    chosen = []
    remaining = list(words)
    while todo:
        best = None
        best_gain = 0
        best_score = -1e9
        for entry in remaining:
            gain = sum(1 for r in entry[1] if bare(r) in todo)
            if gain > best_gain or (gain == best_gain and gain > 0 and
                                    entry[2] > best_score):
                best, best_gain, best_score = entry, gain, entry[2]
        if best is None:
            break  # nothing left can reach the rest
        chosen.append(best)
        remaining.remove(best)
        for reading in best[1]:
            todo.discard(bare(reading))

    lines = [
        "// Generated by scripts/make-filler-lessons.py -- do not edit.",
        "// Two-character dictionary words picked by greedy set cover so the",
        "// drills reach %d%% of single-character usage." % round(USAGE_TARGET * 100),
        "",
    ]
    per_lesson = WORDS_PER_SENTENCE * SENTENCES_PER_LESSON
    for index in range(0, len(chosen), per_lesson):
        block = chosen[index:index + per_lesson]
        number = index // per_lesson + 1
        lines.append("#id=filler%d" % number)
        lines.append("#title=補完 %d：全鍵位掃描" % number)
        lines.append(
            "#intro=這一課不是文章，是為了把前面沒練到的注音組合補齊而從詞庫挑出來的常用詞。"
            "每行五個詞，中間有一個逗號，打完一整行才按 Enter。")
        for start in range(0, len(block), WORDS_PER_SENTENCE):
            row = [word for word, _, _ in block[start:start + WORDS_PER_SENTENCE]]
            # A comma part way through: the drill only presses Enter at a
            # full stop, so this is where the comma key gets practised.
            head, tail = row[:2], row[2:]
            text = " ".join(head)
            if tail:
                text += " ， " + " ".join(tail)
            lines.append(text + " 。")
        lines.append("")

    with io.open(args.out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))

    reached = covered | {bare(r) for _, readings, _ in chosen for r in readings}
    usage = sum(w for s, w in mass.items() if s in reached) / total
    print("filler words: %d in %d lessons" % (len(chosen),
                                              (len(chosen) + per_lesson - 1) //
                                              per_lesson))
    print("syllables reachable: %d/%d (%.2f%% of usage)" %
          (len(reached & set(mass)), len(mass), 100.0 * usage))
    if todo:
        print("still uncovered (%d): %s" % (len(todo), " ".join(sorted(todo))))
    print("wrote %s" % args.out)


if __name__ == "__main__":
    main()
